# Generated by Django 3.2.7 on 2021-12-07 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('squares', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), size=None)),
                ('direction', models.CharField(max_length=1)),
            ],
        ),
    ]
